### ISSUE TITLE
Does not compile on Humble

### ISSUE THREAD

**Issue by Russ76** [TheNoobInventor/diff_drive_pca9685#1]
This is on Ubuntu 22.04 and Humble, on the Raspberry Pi. 

jeff@raspberrypi:~/diff_drive_ws$ colcon build --symlink-install
Starting >>> diff_drive_pca9685
[Processing: diff_drive_pca9685]                             
--- stderr: diff_drive_pca9685                               
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:6:1: error: ‘DiffDrivePCA9685’ does not name a type
    6 | DiffDrivePCA9685::DiffDrivePCA9685()
      | ^~~~~~~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:10:16: error: ‘DiffDrivePCA9685’ has not been declared
   10 | CallbackReturn DiffDrivePCA9685::on_init(const hardware_interface::HardwareInfo & info)
      |                ^~~~~~~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: In function ‘hardware_interface::CallbackReturn diff_drive_9685::on_init(const hardware_interface::HardwareInfo&)’:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:12:53: error: cannot call member function ‘virtual rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn hardware_interface::SystemInterface::on_init(const hardware_interface::HardwareInfo&)’ without object
   12 |     if (hardware_interface::SystemInterface::on_init(info) != CallbackReturn::SUCCESS)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from /opt/ros/humble/include/rclcpp/rclcpp/client.hpp:40,
                 from /opt/ros/humble/include/rclcpp/rclcpp/callback_group.hpp:24,
                 from /opt/ros/humble/include/rclcpp/rclcpp/any_executable.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategy.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategies.hpp:18,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor_options.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor.hpp:37,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors.hpp:21,
                 from /opt/ros/humble/include/rclcpp/rclcpp/rclcpp.hpp:155,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/include/diff_drive_pca9685/diff_drive_pca9685.hpp:16,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:1:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:17:17: error: ‘logger_’ was not declared in this scope
   17 |     RCLCPP_INFO(logger_, "Initializing...");
      |                 ^~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:17:5: error: template argument 1 is invalid
   17 |     RCLCPP_INFO(logger_, "Initializing...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:17:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   17 |     RCLCPP_INFO(logger_, "Initializing...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:17:5: error: template argument 1 is invalid
   17 |     RCLCPP_INFO(logger_, "Initializing...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:17:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   17 |     RCLCPP_INFO(logger_, "Initializing...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:17:5: error: template argument 1 is invalid
   17 |     RCLCPP_INFO(logger_, "Initializing...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:19:5: error: ‘config_’ was not declared in this scope
   19 |     config_.left_wheel_name = info_.hardware_parameters["left_wheel_name"];
      |     ^~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:19:31: error: ‘info_’ was not declared in this scope; did you mean ‘info’?
   19 |     config_.left_wheel_name = info_.hardware_parameters["left_wheel_name"];
      |                               ^~~~~
      |                               info
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:25:5: error: ‘left_wheel_’ was not declared in this scope; did you mean ‘left_wheel_pulse’?
   25 |     left_wheel_.setup(config_.left_wheel_name, config_.enc_ticks_per_rev);
      |     ^~~~~~~~~~~
      |     left_wheel_pulse
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:26:5: error: ‘right_wheel_’ was not declared in this scope; did you mean ‘right_wheel_pulse’?
   26 |     right_wheel_.setup(config_.right_wheel_name, config_.enc_ticks_per_rev);
      |     ^~~~~~~~~~~~
      |     right_wheel_pulse
In file included from /opt/ros/humble/include/rclcpp/rclcpp/client.hpp:40,
                 from /opt/ros/humble/include/rclcpp/rclcpp/callback_group.hpp:24,
                 from /opt/ros/humble/include/rclcpp/rclcpp/any_executable.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategy.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategies.hpp:18,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor_options.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor.hpp:37,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors.hpp:21,
                 from /opt/ros/humble/include/rclcpp/rclcpp/rclcpp.hpp:155,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/include/diff_drive_pca9685/diff_drive_pca9685.hpp:16,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:1:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:28:17: error: ‘logger_’ was not declared in this scope
   28 |     RCLCPP_INFO(logger_, "Finished initialization");
      |                 ^~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:28:5: error: template argument 1 is invalid
   28 |     RCLCPP_INFO(logger_, "Finished initialization");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:28:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   28 |     RCLCPP_INFO(logger_, "Finished initialization");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:28:5: error: template argument 1 is invalid
   28 |     RCLCPP_INFO(logger_, "Finished initialization");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:28:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   28 |     RCLCPP_INFO(logger_, "Finished initialization");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:28:5: error: template argument 1 is invalid
   28 |     RCLCPP_INFO(logger_, "Finished initialization");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: At global scope:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:33:49: error: ‘DiffDrivePCA9685’ has not been declared
   33 | std::vector<hardware_interface::StateInterface> DiffDrivePCA9685::export_state_interfaces()
      |                                                 ^~~~~~~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: In function ‘std::vector<hardware_interface::StateInterface> diff_drive_9685::export_state_interfaces()’:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:39:70: error: ‘left_wheel_’ was not declared in this scope; did you mean ‘left_wheel_pulse’?
   39 | _interfaces.emplace_back(hardware_interface::StateInterface(left_wheel_.name, hardware_interface::HW_IF_VELOCITY, &left_wheel_.velocity));
      |                                                             ^~~~~~~~~~~
      |                                                             left_wheel_pulse
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:41:70: error: ‘right_wheel_’ was not declared in this scope; did you mean ‘right_wheel_pulse’?
   41 | _interfaces.emplace_back(hardware_interface::StateInterface(right_wheel_.name, hardware_interface::HW_IF_VELOCITY, &right_wheel_.velocity));
      |                                                             ^~~~~~~~~~~~
      |                                                             right_wheel_pulse
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: At global scope:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:47:51: error: ‘DiffDrivePCA9685’ has not been declared
   47 | std::vector<hardware_interface::CommandInterface> DiffDrivePCA9685::export_command_interfaces()
      |                                                   ^~~~~~~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: In function ‘std::vector<hardware_interface::CommandInterface> diff_drive_9685::export_command_interfaces()’:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:53:74: error: ‘left_wheel_’ was not declared in this scope; did you mean ‘left_wheel_pulse’?
   53 | nterfaces.emplace_back(hardware_interface::CommandInterface(left_wheel_.name, hardware_interface::HW_IF_VELOCITY, &left_wheel_.command));
      |                                                             ^~~~~~~~~~~
      |                                                             left_wheel_pulse
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:54:74: error: ‘right_wheel_’ was not declared in this scope; did you mean ‘right_wheel_pulse’?
   54 | nterfaces.emplace_back(hardware_interface::CommandInterface(right_wheel_.name, hardware_interface::HW_IF_VELOCITY, &right_wheel_.command));
      |                                                             ^~~~~~~~~~~~
      |                                                             right_wheel_pulse
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: At global scope:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:59:16: error: ‘DiffDrivePCA9685’ has not been declared
   59 | CallbackReturn DiffDrivePCA9685::on_configure(const rclcpp_lifecycle::State & /*previous_state*/)
      |                ^~~~~~~~~~~~~~~~
In file included from /opt/ros/humble/include/rclcpp/rclcpp/client.hpp:40,
                 from /opt/ros/humble/include/rclcpp/rclcpp/callback_group.hpp:24,
                 from /opt/ros/humble/include/rclcpp/rclcpp/any_executable.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategy.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategies.hpp:18,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor_options.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor.hpp:37,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors.hpp:21,
                 from /opt/ros/humble/include/rclcpp/rclcpp/rclcpp.hpp:155,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/include/diff_drive_pca9685/diff_drive_pca9685.hpp:16,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:1:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: In function ‘hardware_interface::CallbackReturn diff_drive_9685::on_configure(const rclcpp_lifecycle::State&)’:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:61:17: error: ‘logger_’ was not declared in this scope
   61 |     RCLCPP_INFO(logger_, "Configuring motors and encoders...");
      |                 ^~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:61:5: error: template argument 1 is invalid
   61 |     RCLCPP_INFO(logger_, "Configuring motors and encoders...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:61:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   61 |     RCLCPP_INFO(logger_, "Configuring motors and encoders...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:61:5: error: template argument 1 is invalid
   61 |     RCLCPP_INFO(logger_, "Configuring motors and encoders...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:61:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   61 |     RCLCPP_INFO(logger_, "Configuring motors and encoders...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:61:5: error: template argument 1 is invalid
   61 |     RCLCPP_INFO(logger_, "Configuring motors and encoders...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:81:17: error: ‘logger_’ was not declared in this scope
   81 |     RCLCPP_INFO(logger_, "Successfully configured motors and encoders!");
      |                 ^~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:81:5: error: template argument 1 is invalid
   81 |     RCLCPP_INFO(logger_, "Successfully configured motors and encoders!");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:81:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   81 |     RCLCPP_INFO(logger_, "Successfully configured motors and encoders!");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:81:5: error: template argument 1 is invalid
   81 |     RCLCPP_INFO(logger_, "Successfully configured motors and encoders!");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:81:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   81 |     RCLCPP_INFO(logger_, "Successfully configured motors and encoders!");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:81:5: error: template argument 1 is invalid
   81 |     RCLCPP_INFO(logger_, "Successfully configured motors and encoders!");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: At global scope:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:86:16: error: ‘DiffDrivePCA9685’ has not been declared
   86 | CallbackReturn DiffDrivePCA9685::on_activate(const rclcpp_lifecycle::State & /*previous_state*/)
      |                ^~~~~~~~~~~~~~~~
In file included from /opt/ros/humble/include/rclcpp/rclcpp/client.hpp:40,
                 from /opt/ros/humble/include/rclcpp/rclcpp/callback_group.hpp:24,
                 from /opt/ros/humble/include/rclcpp/rclcpp/any_executable.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategy.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategies.hpp:18,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor_options.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor.hpp:37,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors.hpp:21,
                 from /opt/ros/humble/include/rclcpp/rclcpp/rclcpp.hpp:155,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/include/diff_drive_pca9685/diff_drive_pca9685.hpp:16,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:1:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: In function ‘hardware_interface::CallbackReturn diff_drive_9685::on_activate(const rclcpp_lifecycle::State&)’:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:88:17: error: ‘logger_’ was not declared in this scope
   88 |     RCLCPP_INFO(logger_, "Starting controller ...");
      |                 ^~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:88:5: error: template argument 1 is invalid
   88 |     RCLCPP_INFO(logger_, "Starting controller ...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:88:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   88 |     RCLCPP_INFO(logger_, "Starting controller ...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:88:5: error: template argument 1 is invalid
   88 |     RCLCPP_INFO(logger_, "Starting controller ...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:88:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   88 |     RCLCPP_INFO(logger_, "Starting controller ...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:88:5: error: template argument 1 is invalid
   88 |     RCLCPP_INFO(logger_, "Starting controller ...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: At global scope:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:93:16: error: ‘DiffDrivePCA9685’ has not been declared
   93 | CallbackReturn DiffDrivePCA9685::on_deactivate(const rclcpp_lifecycle::State & /*previous_state*/)
      |                ^~~~~~~~~~~~~~~~
In file included from /opt/ros/humble/include/rclcpp/rclcpp/client.hpp:40,
                 from /opt/ros/humble/include/rclcpp/rclcpp/callback_group.hpp:24,
                 from /opt/ros/humble/include/rclcpp/rclcpp/any_executable.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategy.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategies.hpp:18,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor_options.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor.hpp:37,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors.hpp:21,
                 from /opt/ros/humble/include/rclcpp/rclcpp/rclcpp.hpp:155,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/include/diff_drive_pca9685/diff_drive_pca9685.hpp:16,
                 from /home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:1:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: In function ‘hardware_interface::CallbackReturn diff_drive_9685::on_deactivate(const rclcpp_lifecycle::State&)’:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:95:17: error: ‘logger_’ was not declared in this scope
   95 |     RCLCPP_INFO(logger_, "Stopping Controller...");
      |                 ^~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:95:5: error: template argument 1 is invalid
   95 |     RCLCPP_INFO(logger_, "Stopping Controller...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:95:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   95 |     RCLCPP_INFO(logger_, "Stopping Controller...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:95:5: error: template argument 1 is invalid
   95 |     RCLCPP_INFO(logger_, "Stopping Controller...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:95:5: error: ‘<declaration error>’ is not a template [-fpermissive]
   95 |     RCLCPP_INFO(logger_, "Stopping Controller...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:95:5: error: template argument 1 is invalid
   95 |     RCLCPP_INFO(logger_, "Stopping Controller...");
      |     ^~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: At global scope:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:100:13: error: ‘DiffDrivePCA9685’ has not been declared
  100 | return_type DiffDrivePCA9685::read(const rclcpp::Time & /*time*/, const rclcpp::Duration & period)
      |             ^~~~~~~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: In function ‘hardware_interface::return_type diff_drive_9685::read(const rclcpp::Time&, const rclcpp::Duration&)’:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:106:26: error: ‘left_wheel_’ was not declared in this scope; did you mean ‘left_wheel_pulse’?
  106 |     read_encoder_values(&left_wheel_.encoder_ticks, &right_wheel_.encoder_ticks);
      |                          ^~~~~~~~~~~
      |                          left_wheel_pulse
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:106:54: error: ‘right_wheel_’ was not declared in this scope; did you mean ‘right_wheel_pulse’?
  106 |     read_encoder_values(&left_wheel_.encoder_ticks, &right_wheel_.encoder_ticks);
      |                                                      ^~~~~~~~~~~~
      |                                                      right_wheel_pulse
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: At global scope:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:120:13: error: ‘DiffDrivePCA9685’ has not been declared
  120 | return_type DiffDrivePCA9685::write(const rclcpp::Time & /*time*/, const rclcpp::Duration & period)
      |             ^~~~~~~~~~~~~~~~
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp: In function ‘hardware_interface::return_type diff_drive_9685::write(const rclcpp::Time&, const rclcpp::Duration&)’:
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:122:41: error: ‘left_wheel_’ was not declared in this scope; did you mean ‘left_wheel_pulse’?
  122 |     double left_motor_counts_per_loop = left_wheel_.command / left_wheel_.rads_per_tick / config_.loop_rate;
      |                                         ^~~~~~~~~~~
      |                                         left_wheel_pulse
/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:122:91: error: ‘config_’ was not declared in this scope
  122 | er_loop = left_wheel_.command / left_wheel_.rads_per_tick / config_.loop_rate;
      |                                                             ^~~~~~~

/home/jeff/diff_drive_ws/src/diff_drive_pca9685/src/diff_drive_pca9685.cpp:123:42: error: ‘right_wheel_’ was not declared in this scope; did you mean ‘right_wheel_pulse’?
  123 |     double right_motor_counts_per_loop = right_wheel_.command / right_wheel_.rads_per_tick / config_.loop_rate;
      |                                          ^~~~~~~~~~~~
      |                                          right_wheel_pulse
gmake[2]: *** [CMakeFiles/diff_drive_pca9685.dir/build.make:76: CMakeFiles/diff_drive_pca9685.dir/src/diff_drive_pca9685.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/diff_drive_pca9685.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< diff_drive_pca9685 [30.7s, exited with code 2]

Summary: 0 packages finished [35.2s]
  1 package failed: diff_drive_pca9685
  1 package had stderr output: diff_drive_pca9685
jeff@raspberrypi:~/diff_drive_ws$

**Comment by TheNoobInventor** [comment]
I apologize for the late reply, I am only seeing this now. Were you able to figure it out?

I have updated this on my lidarbot repository, inside the [lidarbot_base package](https://github.com/TheNoobInventor/lidarbot/tree/main/lidarbot_base),  which uses ROS2 Humble. However, I will try to get this repository updated as soon as possible
